# file: 00-namespace.yaml
apiVersion: v1                      # Versión de la API core usada para namespaces.
kind: Namespace                     # Tipo de recurso: Namespace aísla lógicamente los objetos.
metadata:
  name: namespace-prueba-java       # Nombre del namespace donde vivirá todo lo de la app.
  labels:
    purpose: prod-demo              # Etiqueta útil para agrupar/filtrar recursos por finalidad.

# ----------------------------------------------------------------------
# Buenas prácticas
# - Usar un namespace propio evita mezclar recursos con default u otros equipos.
# - Etiquetar el namespace facilita auditorías y políticas (OPA, Kyverno, etc.).
