# file: 01-service-account.yaml
apiVersion: v1                      # API core: ServiceAccount está en v1.
kind: ServiceAccount                # Recurso para identidades de pods (tokens montados).
metadata:
  name: prueba-java-sa              # Nombre claro y relacionado con la app.
  namespace: namespace-prueba-java        # Debe existir el namespace antes de aplicar esto.
  labels:
    app: prueba-java                # Mismas etiquetas que el resto de objetos de la app.
automountServiceAccountToken: true  # Montar el token del SA en el Pod; necesario si el Pod habla con el API server.

# ----------------------------------------------------------------------
# Buenas prácticas
# - No usar el ServiceAccount "default". Crear uno por app o por microservicio.
# - Si no se necesita acceso al API server, establecer automountServiceAccountToken: false.
